-- MySQL Script generated by MySQL Workbench
-- Fri Oct  7 14:13:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema attendance
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `attendance`;

-- -----------------------------------------------------
-- Schema attendance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `attendance` DEFAULT CHARACTER SET utf8;
USE `attendance`;

-- -----------------------------------------------------
-- Table `attendance`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendance`.`student`;

CREATE TABLE IF NOT EXISTS `attendance`.`student`
(
    `id`           INT         NOT NULL AUTO_INCREMENT,
    `first_name`   VARCHAR(45) NOT NULL,
    `last_name`    VARCHAR(45) NOT NULL,
    `email`        VARCHAR(45) NULL,
    `joining_date` DATETIME    NULL,
    `birthday`     DATETIME    NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendance`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendance`.`teacher`;

CREATE TABLE IF NOT EXISTS `attendance`.`teacher`
(
    `id`         INT         NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(45) NOT NULL,
    `last_name`  VARCHAR(45) NOT NULL,
    `birthday`   VARCHAR(45) NOT NULL,
    `email`      VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendance`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendance`.`subject`;

CREATE TABLE IF NOT EXISTS `attendance`.`subject`
(
    `id`     INT         NOT NULL AUTO_INCREMENT,
    `name`   VARCHAR(45) NOT NULL,
    `credit` INT         NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendance`.`attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendance`.`attendance`;

CREATE TABLE IF NOT EXISTS `attendance`.`attendance`
(
    `id`         INT      NOT NULL AUTO_INCREMENT,
    `date`       DATETIME NOT NULL,
    `teacher_id` INT      NOT NULL,
    `subject_id` INT      NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_Attendance_teacher1_idx` (`teacher_id` ASC),
    INDEX `fk_Attendance_subject1_idx` (`subject_id` ASC),
    CONSTRAINT `fk_attendance_teacher1`
        FOREIGN KEY (`teacher_id`)
            REFERENCES `attendance`.`teacher` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_attendance_subject1`
        FOREIGN KEY (`subject_id`)
            REFERENCES `attendance`.`subject` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendance`.`student_has_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendance`.`student_has_subject`;

CREATE TABLE IF NOT EXISTS `attendance`.`student_has_subject`
(
    `student_id` INT NOT NULL,
    `subject_id` INT NOT NULL,
    PRIMARY KEY (`student_id`, `subject_id`),
    INDEX `fk_student_has_subject_subject1_idx` (`subject_id` ASC),
    INDEX `fk_student_has_subject_student1_idx` (`student_id` ASC),
    CONSTRAINT `fk_student_has_subject_student1`
        FOREIGN KEY (`student_id`)
            REFERENCES `attendance`.`student` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_student_has_subject_subject1`
        FOREIGN KEY (`subject_id`)
            REFERENCES `attendance`.`subject` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendance`.`teacher_has_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendance`.`teacher_has_subject`;

CREATE TABLE IF NOT EXISTS `attendance`.`teacher_has_subject`
(
    `teacher_id` INT NOT NULL,
    `subject_id` INT NOT NULL,
    PRIMARY KEY (`teacher_id`, `subject_id`),
    INDEX `fk_teacher_has_subject_subject1_idx` (`subject_id` ASC),
    INDEX `fk_teacher_has_subject_teacher1_idx` (`teacher_id` ASC),
    CONSTRAINT `fk_teacher_has_subject_teacher1`
        FOREIGN KEY (`teacher_id`)
            REFERENCES `attendance`.`teacher` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_teacher_has_subject_subject1`
        FOREIGN KEY (`subject_id`)
            REFERENCES `attendance`.`subject` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendance`.`attendance_has_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendance`.`attendance_has_student`;

CREATE TABLE IF NOT EXISTS `attendance`.`attendance_has_student`
(
    `attendance_id` INT         NOT NULL,
    `student_id`    INT         NOT NULL,
    `state`         VARCHAR(45) NOT NULL,
    `comment`       VARCHAR(45) NULL,
    `date`          VARCHAR(45) NOT NULL,
    PRIMARY KEY (`attendance_id`, `student_id`),
    INDEX `fk_attendance_has_student_student1_idx` (`student_id` ASC),
    INDEX `fk_attendance_has_student_attendance1_idx` (`attendance_id` ASC),
    CONSTRAINT `fk_attendance_has_student_attendance1`
        FOREIGN KEY (`attendance_id`)
            REFERENCES `attendance`.`attendance` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_attendance_has_student_student1`
        FOREIGN KEY (`student_id`)
            REFERENCES `attendance`.`student` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
